
CREATE TABLE IPAM_USER
(
  USER_ID             VARCHAR2(32 BYTE)         NOT NULL,
  USER_NAME           VARCHAR2(32 BYTE)         NOT NULL,
  IP_LIST             VARCHAR2(500 BYTE)        NOT NULL,
  OTHER_DESC          VARCHAR2(200 BYTE),
  ALLOW_EXCP          CHAR(1 BYTE)              NOT NULL,
  REG_DATE            VARCHAR2(25 BYTE),
  CHANGE_DATE         VARCHAR2(25 BYTE),
  BATCH_UPDATED_FLAG  CHAR(1 BYTE)              DEFAULT 'f',
  LAST_ACCESS_IP      VARCHAR2(25 BYTE),
  LAST_ACCESS_TIME    VARCHAR2(25 BYTE)
);


ALTER TABLE IPAM_USER
       ADD  PRIMARY KEY (USER_ID);
       

CREATE INDEX XIPAM_USER_NAME ON IPAM_USER
(
       USER_NAME                 ASC
);

COMMENT ON COLUMN IPAM_USER.USER_ID IS '사용자사번';

COMMENT ON COLUMN IPAM_USER.USER_NAME IS '사용자이름';

COMMENT ON COLUMN IPAM_USER.IP_LIST IS '접속허용 IP 목록';

COMMENT ON COLUMN IPAM_USER.OTHER_DESC IS '기타 설명';

COMMENT ON COLUMN IPAM_USER.ALLOW_EXCP IS '접속허용 예외설정 t=예외허용,f=예외허용금지';

COMMENT ON COLUMN IPAM_USER.REG_DATE IS '사용자등록 시간';

COMMENT ON COLUMN IPAM_USER.CHANGE_DATE IS '사용자변경 시간';

COMMENT ON COLUMN IPAM_USER.BATCH_UPDATED_FLAG IS '배치프로그램 실행시 사용됨';

COMMENT ON COLUMN IPAM_USER.LAST_ACCESS_IP IS '마지막접속허용 IP';

COMMENT ON COLUMN IPAM_USER.LAST_ACCESS_TIME IS '마지막 접속허용 시간';

